# github action to run bash
name: run bash
on:
  push
jobs:
  run-bash:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2 
      - name: show file
        run: |
          pwd
          ls -la
          cd ../
          ls -la
      - name: just-run
        run: sh run.sh